# Generated by Django 3.1.3 on 2020-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenemeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='İsim')),
                ('soyisim', models.TextField(max_length=100, verbose_name='Soyisim')),
                ('telefon', models.TextField(max_length=11, verbose_name='Telefon')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Yayım Zamanı')),
            ],
        ),
    ]
