# Generated by Django 3.1.4 on 2020-12-13 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IletiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilgi', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('eposta', models.EmailField(max_length=100, verbose_name='E Posta')),
                ('mesaj', models.TextField(verbose_name='Mesajınız')),
                ('gonderi_tar', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
