# Generated by Django 3.1.4 on 2020-12-12 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GonderiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('yazi', models.TextField()),
                ('kayit_zaman', models.DateTimeField(default=django.utils.timezone.now)),
                ('yayim_tarihi', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
