# Generated by Django 3.1.4 on 2020-12-13 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gonderimodel',
            name='yayim_zaman',
        ),
        migrations.AddField(
            model_name='gonderimodel',
            name='telno',
            field=models.IntegerField(blank=True, null=True, verbose_name='NO'),
        ),
        migrations.AddField(
            model_name='gonderimodel',
            name='yayim_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayım Zamanı'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='baslik',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='kayit_zaman',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kayıt Zamanı'),
        ),
        migrations.AlterField(
            model_name='gonderimodel',
            name='yazi',
            field=models.TextField(verbose_name='Yazı'),
        ),
    ]
