# Generated by Django 3.1.4 on 2020-12-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201213_1613'),
        ('blog', '0002_auto_20201213_1614'),
    ]

    operations = [
    ]
