# Generated by Django 3.1.4 on 2020-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_20201213_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='gonderimodel',
            name='telefonnno',
            field=models.IntegerField(default='05000000000', max_length=10, verbose_name='Telefon numaranız'),
        ),
    ]
